CREATE TABLE IF NOT EXISTS endereco (
  idEndereco INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rua VARCHAR(100) NOT NULL,
  bairro VARCHAR(100) NOT NULL,
  numero INT NOT NULL,
  cep VARCHAR(20) NOT NULL
);